[package]
name = "Stringnalyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.5"
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
once_cell = "*"